project:
  type: manuscript
  output-dir: docs

manuscript:
  article: index.qmd

format:
  html: default
  pdf: default
  # docx: default
  # jats: default

  # (other formats)
  # pdf: default

execute:
  freeze: true



